name: Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          
      - name: Check version changes
        uses: EndBug/version-check@v1.0.0 # More info about the arguments on the action page
        id: check # This will be the reference for later
  
      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change! -> ${{ steps.check.outputs.type }}"'
        
      - name: Publish package
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
